version: "2.1"

services:
  python-flask-demo:
    build: ./python-flask-demo
    privileged: true
    restart: always
    ports:
      - "5000:5000"
    devices:
      - "/dev/video0:/dev/video0"
  react-demo:
    build: ./react-demo
    ports:
      - "3000:3000"
    volumes:
      - shared-data:/data

  express-demo:
    build: ./express-demo
    ports:
      - "3001:3000"
    volumes:
      - shared-data:/data

  c-demo:
    build: ./c-demo
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/data

  instrument-control:
    build: ./instrument-control
    privileged: true
    restart: always
    ports:
      - "8081:8080"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"


    scpi-sim:
      build: ./scpi-sim
      restart: always
      ports:
        - "5025:5025"
        
volumes:
  shared-data: