version: "2.1"

services:
  python-flask:
    build: .
    privileged: true
    ports:
      - "5000:5000"
    volumes:
      - shared-data:/data

  react-demo:
    build: ./react-demo
    ports:
      - "3000:3000"
    volumes:
      - shared-data:/data

volumes:
  shared-data: